

export const evidenceSubmissions = [
  { id: '1', site: 'Kurnool Solar Plant', element: 'Near Miss Reporting Rate & Follow-up', elementNumber: 1, subElement: 'Near miss reporting rate per month', submittedBy: 'Arun Kumar', date: '2026-03-06 10:30', filesCount: 3, status: 'APPROVED', notes: 'Monthly near miss log and follow-up tracker.', marksAwarded: 4.5, remarks: 'Good documentation.' },
  { id: '2', site: 'Kurnool Solar Plant', element: 'Near Miss Reporting Rate & Follow-up', elementNumber: 1, subElement: 'Follow-up closure rate', submittedBy: 'Arun Kumar', date: '2026-03-06 10:45', filesCount: 2, status: 'APPROVED', notes: 'Closure tracker attached.', marksAwarded: 4, remarks: 'Satisfactory.' },
  { id: '3', site: 'Kurnool Solar Plant', element: 'Safety Training Completion Rate & Effectiveness', elementNumber: 2, subElement: 'Training completion percentage', submittedBy: 'Arun Kumar', date: '2026-03-07 09:00', filesCount: 4, status: 'PENDING', notes: 'Training records for all staff. 98% completion.', marksAwarded: null },
  { id: '4', site: 'Kurnool Solar Plant', element: 'Safety Training Completion Rate & Effectiveness', elementNumber: 2, subElement: 'Training effectiveness score', submittedBy: 'Arun Kumar', date: '2026-03-07 09:15', filesCount: 2, status: 'PENDING', notes: 'Quiz results showing 85% average pass rate.', marksAwarded: null },
  { id: '5', site: 'Kurnool Solar Plant', element: 'Adherence to LOTO, PTW and other Procedures', elementNumber: 4, subElement: 'PTW compliance rate', submittedBy: 'Arun Kumar', date: '2026-03-05 14:00', filesCount: 5, status: 'REJECTED', notes: 'PTW register for Q3.', marksAwarded: null, rejectionReason: 'PTW register incomplete — missing December entries.' },
  { id: '6', site: 'Anantapur Wind Farm', element: 'Near Miss Reporting Rate & Follow-up', elementNumber: 1, subElement: 'Near miss reporting rate per month', submittedBy: 'Vijay Singh', date: '2026-03-04 11:00', filesCount: 3, status: 'PENDING', notes: 'Monthly report with trend analysis.', marksAwarded: null },
  { id: '7', site: 'Anantapur Wind Farm', element: 'Safety Training Completion Rate & Effectiveness', elementNumber: 2, subElement: 'Training completion percentage', submittedBy: 'Vijay Singh', date: '2026-03-03 16:00', filesCount: 2, status: 'APPROVED', notes: '100% completion achieved.', marksAwarded: 5, remarks: 'Excellent. Full marks.' },
  { id: '8', site: 'Kurnool Solar Plant', element: 'Demonstrated Leadership Commitment & Safety Culture', elementNumber: 5, subElement: 'Management safety walks', submittedBy: 'Arun Kumar', date: '2026-03-08 08:00', filesCount: 6, status: 'PENDING', notes: 'Photos and logs of 3 safety walks.', marksAwarded: null },
  { id: '9', site: 'Kurnool Solar Plant', element: 'Adoption of Best Practices & Continuous Improvement', elementNumber: 7, subElement: 'Best practices implemented', submittedBy: 'Arun Kumar', date: '2026-03-02 10:00', filesCount: 3, status: 'REJECTED', notes: 'Documented 2 new safety practices.', marksAwarded: null, rejectionReason: 'Evidence insufficient. Need before/after comparison.' },
  { id: '10', site: 'Kurnool Solar Plant', element: 'Compliance & Readiness', elementNumber: 8, subElement: 'Legal compliance status', submittedBy: 'Arun Kumar', date: '2026-03-01 09:00', filesCount: 4, status: 'APPROVED', notes: 'All licenses current. Compliance matrix attached.', marksAwarded: 4.5, remarks: 'All in order.' },
];
