export const sites = [
  { id: '1', name: 'TS_DOM/Sunborne', cluster: 'TS - Pardhasaradhi', type: 'Solar', capacity: 35.00, siteHead: 'Pardhasaradhi', status: 'Active', dso: 'Admin' },
  { id: '2', name: 'TS_MV-REG', cluster: 'TS - Yesubabu', type: 'Solar', capacity: 10.00, siteHead: 'Yesubabu.p', status: 'Active', dso: 'Admin' },
  { id: '3', name: 'TS_Premier-Talmadla', cluster: 'TS - Yesubabu', type: 'Solar', capacity: 10.00, siteHead: 'A S Lakshmi Narayana', status: 'Active', dso: 'Admin' },
  { id: '4', name: 'TS_Premier-Narsinghi', cluster: 'TS - Yesubabu', type: 'Solar', capacity: 8.00, siteHead: 'Mahesh Bojja', status: 'Active', dso: 'Admin' },
  { id: '5', name: 'TS_MV-JGP', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 10.00, siteHead: 'K V Jagadeesh Kumar', status: 'Active', dso: 'Admin' },
  { id: '6', name: 'TS_Pennar-Bhujrampet', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 8.04, siteHead: 'Bhumesh Chary', status: 'Active', dso: 'Admin' },
  { id: '7', name: 'TS_Premier-Digwal', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 8.00, siteHead: 'Ravi shankar', status: 'Active', dso: 'Admin' },
  { id: '8', name: 'TS_Karvy-Sadasivpet', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 20.00, siteHead: 'Krishna Chaitanya', status: 'Active', dso: 'Admin' },
  { id: '9', name: 'TS_Jilesh', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 45.00, siteHead: 'Prasad Vaka', status: 'Active', dso: 'Admin' },
  { id: '10', name: 'TS_Karvy-Viswarupa', cluster: 'TS - Jagadeesh', type: 'Solar', capacity: 10.00, siteHead: 'Prasad Vaka', status: 'Active', dso: 'Admin' },
  { id: '11', name: 'TS_Karvy-Achintya I', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Sravankumar.v', status: 'Active', dso: 'Admin' },
  { id: '12', name: 'TS_Karvy-Achintya II', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Sravankumar.v', status: 'Active', dso: 'Admin' },
  { id: '13', name: 'TS_Karvy-Grinibrith', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Sravankumar.v', status: 'Active', dso: 'Admin' },
  { id: '14', name: 'TS_Karvy-Suvarchas', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Sravankumar.v', status: 'Active', dso: 'Admin' },
  { id: '15', name: 'TS_Pennar-Peddalingapur', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Ganesh Gaadi', status: 'Active', dso: 'Admin' },
  { id: '16', name: 'TS_Pennar-Mankondur', cluster: 'TS - Sravan', type: 'Solar', capacity: 5.00, siteHead: 'Srinivas Kontu', status: 'Active', dso: 'Admin' },
  { id: '17', name: 'TS_Premier-Chennur', cluster: 'TS - Sravan', type: 'Solar', capacity: 10.00, siteHead: 'Prashanth G', status: 'Active', dso: 'Admin' },
  { id: '18', name: 'TS_Zuka', cluster: 'TS - Bala Ravikanth', type: 'Solar', capacity: 47.70, siteHead: 'Bala Ravikanth G', status: 'Active', dso: 'Admin' },
];
