export const users = [
  { id: '1', name: 'HO Admin', email: 'ho@greenko.com', password: 'password', roles: ['HEAD_OFFICE'], status: 'Active', avatar: 'HA' },
  { id: '2', name: 'Pedda Pullayya', email: 'pullayya@greenko.com', password: 'password', roles: ['CLUSTER_SAFETY_OFFICER'], accessibleClusters: ['TS - Pardhasaradhi', 'TS - Yesubabu', 'TS - Jagadeesh', 'TS - Bala Ravikanth'], status: 'Active', avatar: 'PP' },
  { id: '3', name: 'REMIJIOUS', email: 'remijious@greenko.com', password: 'password', roles: ['CLUSTER_SAFETY_OFFICER'], accessibleClusters: ['TS - Jagadeesh', 'TS - Sravan'], status: 'Active', avatar: 'R' },
  { id: '4', name: 'Pardhasaradhi', email: 'pardhasaradhi@greenko.com', password: 'password', roles: ['CLUSTER_HEAD', 'SITE_HEAD'], cluster: 'TS - Pardhasaradhi', site: 'TS_DOM/Sunborne', status: 'Active', avatar: 'P' },
  { id: '5', name: 'Mr. Yesubabu. P', email: 'yesubabu@greenko.com', password: 'password', roles: ['CLUSTER_HEAD', 'SITE_HEAD'], cluster: 'TS - Yesubabu', site: 'TS_MV-REG', status: 'Active', avatar: 'YP' },
  { id: '6', name: 'Mr. K V Jagadeesh Kumar', email: 'jagadeesh@greenko.com', password: 'password', roles: ['CLUSTER_HEAD', 'SITE_HEAD'], cluster: 'TS - Jagadeesh', site: 'TS_MV-JGP', status: 'Active', avatar: 'JK' },
  { id: '7', name: 'Sravankumar.v', email: 'sravan@greenko.com', password: 'password', roles: ['CLUSTER_HEAD', 'SITE_HEAD'], cluster: 'TS - Sravan', site: 'TS_Karvy-Achintya I', status: 'Active', avatar: 'SK' },
  { id: '8', name: 'Bala Ravikanth G', email: 'bala@greenko.com', password: 'password', roles: ['CLUSTER_HEAD', 'SITE_HEAD'], cluster: 'TS - Bala Ravikanth', site: 'TS_Zuka', status: 'Active', avatar: 'BR' },
  { id: '9', name: 'A S Lakshmi Narayana', email: 'lakshmi@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Premier-Talmadla', cluster: 'TS - Yesubabu', status: 'Active', avatar: 'LN' },
  { id: '10', name: 'Mahesh Bojja', email: 'mahesh@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Premier-Narsinghi', cluster: 'TS - Yesubabu', status: 'Active', avatar: 'MB' },
  { id: '11', name: 'Bhumesh Chary', email: 'bhumesh@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Pennar-Bhujrampet', cluster: 'TS - Jagadeesh', status: 'Active', avatar: 'BC' },
  { id: '12', name: 'Ravi shankar', email: 'ravishankar@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Premier-Digwal', cluster: 'TS - Jagadeesh', status: 'Active', avatar: 'RS' },
  { id: '13', name: 'Krishna Chaitanya', email: 'krishna@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Karvy-Sadasivpet', cluster: 'TS - Jagadeesh', status: 'Active', avatar: 'KC' },
  { id: '14', name: 'Prasad Vaka', email: 'prasad@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Jilesh', cluster: 'TS - Jagadeesh', status: 'Active', avatar: 'PV' },
  { id: '15', name: 'Ganesh Gaadi', email: 'ganesh@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Pennar-Peddalingapur', cluster: 'TS - Sravan', status: 'Active', avatar: 'GG' },
  { id: '16', name: 'Srinivas Kontu', email: 'srinivas@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Pennar-Mankondur', cluster: 'TS - Sravan', status: 'Active', avatar: 'SK' },
  { id: '17', name: 'Prashanth G', email: 'prashanth@greenko.com', password: 'password', roles: ['SITE_HEAD'], site: 'TS_Premier-Chennur', cluster: 'TS - Sravan', status: 'Active', avatar: 'PG' },
];
